export { default as BlogsSection } from './BlogsSection';
export { default as BodyContent } from './BodyContent';
export { default as CTAButton } from './CTAButton';
export { default as MainArea } from './MainArea';
export { default as MainContent } from './MainContent';
export { default as MainTitle } from './MainTitle';
export { default as Navigation } from './Navigation';
export { default as SellerCard } from './SellerCard';
export { default as SmallHeading } from './SmallHeading';
